stages:
- test
- name: deploy
  if: tag IS present

language: c
os: linux
dist: trusty

install:
- scripts/install

script:
- scripts/build --test
- scripts/test

.deploy_job_template: &deploy_job_template
  script:
  - scripts/build
  - tar -czf flora-${TRAVIS_TAG}-$(uname)-$(uname -m).tar.gz -C out ./usr
  deploy:
    provider: releases
    api_key:
      secure: wVdyP2Idczya/s6G/gwkJsF/v8QeYdBCC6AxdcyAHNKUZsxaRsM15+eji2sYfA9eZj6dSv4wsRQXGYp0nvuC5b0JBpnTH8wFyURq7DJh4xOb3D3LQsULBWgHVBjwWF3tOJ1jxKralxs8E2A9H9lsT8ee0RCKeX+gGtOUKiU9rOdCezfoPUJjErMGlgYVCSJWg9HQlXiPxyFqDNbY+Z642zKJrWwcBT9Ao3422UJO6zBAVg9xI6PJV8e0+owxY1iHarKycih+MxSTFXHIIq6p9O9ZmZHNXw9Xt34W1m2c/riDnhB1WmhKo74KDIBQJEano6oHCQ4fDahRwiUczTwG3dx5hb6gfEI5SJv7fSmoBh4s9sdozAZ6bnV0NiWhftxUTAgJcoH6L/Sw0tFckb2faYR5CKnRF32VjoAICR4ZBPOiZT9Yq+RLnD+64d2gJG7z4txzRptPiJ3XRx7QQ4LLDERCTcvgfhMxcYaNUyicGy/o+oxDQBws6Mb0eQWibmB8cidJarz3gm+pmwr4RvXZFz0HvkMn0fV0VFqVj7l8oOgHEkosSFUifsI0bhFqF3ibmFr7MJqCnVItaciJuLKtk4buMiQkkAIXql50DLRRiKcxgC3IMs7u8vDP8rtjncZYfybc7g4VHSuMQyGW+xig+8aSJ7SXf3AaVnGxcnfgsFE=
    file_glob: true
    skip_cleanup: true
    file: "./flora-*.tar.gz"
    on:
      repo: yodaos-project/flora
      tags: true

jobs:
  include:
  - stage: test
    os: linux
  - stage: test
    os: osx

  - stage: deploy
    <<: *deploy_job_template
    os: linux
  - stage: deploy
    <<: *deploy_job_template
    os: osx
