
/* Copyright 2015-present Samsung Electronics Co., Ltd. and other contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is generated by tools/js2c.py
 * Do not modify this.
 */
#define JERRY_MAGIC_STRING_ITEMS \
  MAGICSTR_EX_DEF(MAGIC_STR_0, "ca") \
  MAGICSTR_EX_DEF(MAGIC_STR_1, "cwd") \
  MAGICSTR_EX_DEF(MAGIC_STR_2, "end") \
  MAGICSTR_EX_DEF(MAGIC_STR_3, "env") \
  MAGICSTR_EX_DEF(MAGIC_STR_4, "hex") \
  MAGICSTR_EX_DEF(MAGIC_STR_5, "key") \
  MAGICSTR_EX_DEF(MAGIC_STR_6, "pid") \
  MAGICSTR_EX_DEF(MAGIC_STR_7, "pin") \
  MAGICSTR_EX_DEF(MAGIC_STR_8, "ref") \
  MAGICSTR_EX_DEF(MAGIC_STR_9, "url") \
  MAGICSTR_EX_DEF(MAGIC_STR_10, "HOME") \
  MAGICSTR_EX_DEF(MAGIC_STR_11, "IPv4") \
  MAGICSTR_EX_DEF(MAGIC_STR_12, "IPv6") \
  MAGICSTR_EX_DEF(MAGIC_STR_13, "arch") \
  MAGICSTR_EX_DEF(MAGIC_STR_14, "argv") \
  MAGICSTR_EX_DEF(MAGIC_STR_15, "bind") \
  MAGICSTR_EX_DEF(MAGIC_STR_16, "cert") \
  MAGICSTR_EX_DEF(MAGIC_STR_17, "code") \
  MAGICSTR_EX_DEF(MAGIC_STR_18, "copy") \
  MAGICSTR_EX_DEF(MAGIC_STR_19, "data") \
  MAGICSTR_EX_DEF(MAGIC_STR_20, "emit") \
  MAGICSTR_EX_DEF(MAGIC_STR_21, "host") \
  MAGICSTR_EX_DEF(MAGIC_STR_22, "mode") \
  MAGICSTR_EX_DEF(MAGIC_STR_23, "open") \
  MAGICSTR_EX_DEF(MAGIC_STR_24, "ping") \
  MAGICSTR_EX_DEF(MAGIC_STR_25, "pong") \
  MAGICSTR_EX_DEF(MAGIC_STR_26, "port") \
  MAGICSTR_EX_DEF(MAGIC_STR_27, "read") \
  MAGICSTR_EX_DEF(MAGIC_STR_28, "send") \
  MAGICSTR_EX_DEF(MAGIC_STR_29, "stat") \
  MAGICSTR_EX_DEF(MAGIC_STR_30, "stop") \
  MAGICSTR_EX_DEF(MAGIC_STR_31, "abort") \
  MAGICSTR_EX_DEF(MAGIC_STR_32, "board") \
  MAGICSTR_EX_DEF(MAGIC_STR_33, "chdir") \
  MAGICSTR_EX_DEF(MAGIC_STR_34, "close") \
  MAGICSTR_EX_DEF(MAGIC_STR_35, "fstat") \
  MAGICSTR_EX_DEF(MAGIC_STR_36, "iotjs") \
  MAGICSTR_EX_DEF(MAGIC_STR_37, "mkdir") \
  MAGICSTR_EX_DEF(MAGIC_STR_38, "onEnd") \
  MAGICSTR_EX_DEF(MAGIC_STR_39, "owner") \
  MAGICSTR_EX_DEF(MAGIC_STR_40, "pause") \
  MAGICSTR_EX_DEF(MAGIC_STR_41, "rmdir") \
  MAGICSTR_EX_DEF(MAGIC_STR_42, "slice") \
  MAGICSTR_EX_DEF(MAGIC_STR_43, "start") \
  MAGICSTR_EX_DEF(MAGIC_STR_44, "stats") \
  MAGICSTR_EX_DEF(MAGIC_STR_45, "unref") \
  MAGICSTR_EX_DEF(MAGIC_STR_46, "write") \
  MAGICSTR_EX_DEF(MAGIC_STR_47, "Buffer") \
  MAGICSTR_EX_DEF(MAGIC_STR_48, "OnBody") \
  MAGICSTR_EX_DEF(MAGIC_STR_49, "base64") \
  MAGICSTR_EX_DEF(MAGIC_STR_50, "config") \
  MAGICSTR_EX_DEF(MAGIC_STR_51, "device") \
  MAGICSTR_EX_DEF(MAGIC_STR_52, "doExit") \
  MAGICSTR_EX_DEF(MAGIC_STR_53, "export") \
  MAGICSTR_EX_DEF(MAGIC_STR_54, "family") \
  MAGICSTR_EX_DEF(MAGIC_STR_55, "finish") \
  MAGICSTR_EX_DEF(MAGIC_STR_56, "isFile") \
  MAGICSTR_EX_DEF(MAGIC_STR_57, "length") \
  MAGICSTR_EX_DEF(MAGIC_STR_58, "listen") \
  MAGICSTR_EX_DEF(MAGIC_STR_59, "method") \
  MAGICSTR_EX_DEF(MAGIC_STR_60, "onData") \
  MAGICSTR_EX_DEF(MAGIC_STR_61, "onping") \
  MAGICSTR_EX_DEF(MAGIC_STR_62, "onread") \
  MAGICSTR_EX_DEF(MAGIC_STR_63, "period") \
  MAGICSTR_EX_DEF(MAGIC_STR_64, "rename") \
  MAGICSTR_EX_DEF(MAGIC_STR_65, "resume") \
  MAGICSTR_EX_DEF(MAGIC_STR_66, "status") \
  MAGICSTR_EX_DEF(MAGIC_STR_67, "stderr") \
  MAGICSTR_EX_DEF(MAGIC_STR_68, "stdout") \
  MAGICSTR_EX_DEF(MAGIC_STR_69, "unlink") \
  MAGICSTR_EX_DEF(MAGIC_STR_70, "wsInit") \
  MAGICSTR_EX_DEF(MAGIC_STR_71, "REQUEST") \
  MAGICSTR_EX_DEF(MAGIC_STR_72, "TlsInit") \
  MAGICSTR_EX_DEF(MAGIC_STR_73, "address") \
  MAGICSTR_EX_DEF(MAGIC_STR_74, "bindRaw") \
  MAGICSTR_EX_DEF(MAGIC_STR_75, "binding") \
  MAGICSTR_EX_DEF(MAGIC_STR_76, "compare") \
  MAGICSTR_EX_DEF(MAGIC_STR_77, "compile") \
  MAGICSTR_EX_DEF(MAGIC_STR_78, "connect") \
  MAGICSTR_EX_DEF(MAGIC_STR_79, "errname") \
  MAGICSTR_EX_DEF(MAGIC_STR_80, "execute") \
  MAGICSTR_EX_DEF(MAGIC_STR_81, "handler") \
  MAGICSTR_EX_DEF(MAGIC_STR_82, "headers") \
  MAGICSTR_EX_DEF(MAGIC_STR_83, "isDevUp") \
  MAGICSTR_EX_DEF(MAGIC_STR_84, "message") \
  MAGICSTR_EX_DEF(MAGIC_STR_85, "methods") \
  MAGICSTR_EX_DEF(MAGIC_STR_86, "onError") \
  MAGICSTR_EX_DEF(MAGIC_STR_87, "onclose") \
  MAGICSTR_EX_DEF(MAGIC_STR_88, "onwrite") \
  MAGICSTR_EX_DEF(MAGIC_STR_89, "readdir") \
  MAGICSTR_EX_DEF(MAGIC_STR_90, "upgrade") \
  MAGICSTR_EX_DEF(MAGIC_STR_91, "version") \
  MAGICSTR_EX_DEF(MAGIC_STR_92, "RESPONSE") \
  MAGICSTR_EX_DEF(MAGIC_STR_93, "_private") \
  MAGICSTR_EX_DEF(MAGIC_STR_94, "bindUser") \
  MAGICSTR_EX_DEF(MAGIC_STR_95, "emitExit") \
  MAGICSTR_EX_DEF(MAGIC_STR_96, "exitCode") \
  MAGICSTR_EX_DEF(MAGIC_STR_97, "isServer") \
  MAGICSTR_EX_DEF(MAGIC_STR_98, "loopback") \
  MAGICSTR_EX_DEF(MAGIC_STR_99, "onClosed") \
  MAGICSTR_EX_DEF(MAGIC_STR_100, "onSocket") \
  MAGICSTR_EX_DEF(MAGIC_STR_101, "platform") \
  MAGICSTR_EX_DEF(MAGIC_STR_102, "readByte") \
  MAGICSTR_EX_DEF(MAGIC_STR_103, "readSync") \
  MAGICSTR_EX_DEF(MAGIC_STR_104, "shutdown") \
  MAGICSTR_EX_DEF(MAGIC_STR_105, "toString") \
  MAGICSTR_EX_DEF(MAGIC_STR_106, "IOTJS_ENV") \
  MAGICSTR_EX_DEF(MAGIC_STR_107, "OnHeaders") \
  MAGICSTR_EX_DEF(MAGIC_STR_108, "TLSSocket") \
  MAGICSTR_EX_DEF(MAGIC_STR_109, "_incoming") \
  MAGICSTR_EX_DEF(MAGIC_STR_110, "addHeader") \
  MAGICSTR_EX_DEF(MAGIC_STR_111, "closeSync") \
  MAGICSTR_EX_DEF(MAGIC_STR_112, "createTCP") \
  MAGICSTR_EX_DEF(MAGIC_STR_113, "onTimeout") \
  MAGICSTR_EX_DEF(MAGIC_STR_114, "onmessage") \
  MAGICSTR_EX_DEF(MAGIC_STR_115, "prototype") \
  MAGICSTR_EX_DEF(MAGIC_STR_116, "readStart") \
  MAGICSTR_EX_DEF(MAGIC_STR_117, "readUInt8") \
  MAGICSTR_EX_DEF(MAGIC_STR_118, "rsaVerify") \
  MAGICSTR_EX_DEF(MAGIC_STR_119, "setFilter") \
  MAGICSTR_EX_DEF(MAGIC_STR_120, "shaEncode") \
  MAGICSTR_EX_DEF(MAGIC_STR_121, "writeSync") \
  MAGICSTR_EX_DEF(MAGIC_STR_122, "wsReceive") \
  MAGICSTR_EX_DEF(MAGIC_STR_123, "HTTPParser") \
  MAGICSTR_EX_DEF(MAGIC_STR_124, "IOTJS_PATH") \
  MAGICSTR_EX_DEF(MAGIC_STR_125, "TlsContext") \
  MAGICSTR_EX_DEF(MAGIC_STR_126, "_reuseAddr") \
  MAGICSTR_EX_DEF(MAGIC_STR_127, "byteLength") \
  MAGICSTR_EX_DEF(MAGIC_STR_128, "byteParsed") \
  MAGICSTR_EX_DEF(MAGIC_STR_129, "http_major") \
  MAGICSTR_EX_DEF(MAGIC_STR_130, "http_minor") \
  MAGICSTR_EX_DEF(MAGIC_STR_131, "onWritable") \
  MAGICSTR_EX_DEF(MAGIC_STR_132, "onpingresp") \
  MAGICSTR_EX_DEF(MAGIC_STR_133, "readSource") \
  MAGICSTR_EX_DEF(MAGIC_STR_134, "servername") \
  MAGICSTR_EX_DEF(MAGIC_STR_135, "setTimeout") \
  MAGICSTR_EX_DEF(MAGIC_STR_136, "status_msg") \
  MAGICSTR_EX_DEF(MAGIC_STR_137, "writeUInt8") \
  MAGICSTR_EX_DEF(MAGIC_STR_138, "_createStat") \
  MAGICSTR_EX_DEF(MAGIC_STR_139, "_onNextTick") \
  MAGICSTR_EX_DEF(MAGIC_STR_140, "bindControl") \
  MAGICSTR_EX_DEF(MAGIC_STR_141, "decodeFrame") \
  MAGICSTR_EX_DEF(MAGIC_STR_142, "getaddrinfo") \
  MAGICSTR_EX_DEF(MAGIC_STR_143, "getsockname") \
  MAGICSTR_EX_DEF(MAGIC_STR_144, "isDirectory") \
  MAGICSTR_EX_DEF(MAGIC_STR_145, "sendRequest") \
  MAGICSTR_EX_DEF(MAGIC_STR_146, "writeDecode") \
  MAGICSTR_EX_DEF(MAGIC_STR_147, "base64Encode") \
  MAGICSTR_EX_DEF(MAGIC_STR_148, "onconnection") \
  MAGICSTR_EX_DEF(MAGIC_STR_149, "setKeepAlive") \
  MAGICSTR_EX_DEF(MAGIC_STR_150, "compileModule") \
  MAGICSTR_EX_DEF(MAGIC_STR_151, "handleTimeout") \
  MAGICSTR_EX_DEF(MAGIC_STR_152, "iflyosProduct") \
  MAGICSTR_EX_DEF(MAGIC_STR_153, "iflyosPlatform") \
  MAGICSTR_EX_DEF(MAGIC_STR_154, "builtin_modules") \
  MAGICSTR_EX_DEF(MAGIC_STR_155, "fromArrayBuffer") \
  MAGICSTR_EX_DEF(MAGIC_STR_156, "onhandshakedone") \
  MAGICSTR_EX_DEF(MAGIC_STR_157, "shouldkeepalive") \
  MAGICSTR_EX_DEF(MAGIC_STR_158, "isAliveExceptFor") \
  MAGICSTR_EX_DEF(MAGIC_STR_159, "prepareHandshake") \
  MAGICSTR_EX_DEF(MAGIC_STR_160, "OnHeadersComplete") \
  MAGICSTR_EX_DEF(MAGIC_STR_161, "OnMessageComplete") \
  MAGICSTR_EX_DEF(MAGIC_STR_162, "debuggerGetSource") \
  MAGICSTR_EX_DEF(MAGIC_STR_163, "debuggerWaitSource") \
  MAGICSTR_EX_DEF(MAGIC_STR_164, "parseHandshakeData") \
  MAGICSTR_EX_DEF(MAGIC_STR_165, "rejectUnauthorized") \
  MAGICSTR_EX_DEF(MAGIC_STR_166, "ReceiveHandshakeData") \
  MAGICSTR_EX_DEF(MAGIC_STR_167, "_onUncaughtException") \
  MAGICSTR_EX_DEF(MAGIC_STR_168, "IOTJS_WORKING_DIR_PATH") \
  MAGICSTR_EX_DEF(MAGIC_STR_169, "IOTJS_EXTRA_MODULE_PATH") \

